<a href="https://colab.research.google.com/github/Gurdeep-kaur533/-assignments_gurdeep.ipynb-assignments_gurdeep.ipynb_/blob/main/assignments_gurdeep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Assignment 2

In [ ]:
# print 1 to 10 stop at 9
for i in range(1,11):
    if i == 9:
        break
    print(i)

1
2
3
4
5
6
7
8


In [ ]:
#stop when user enter -ve number
num = int(input("Enter a number: "))
while num >= 0:
    print(f"you entered: {num}")
    num = int(input("Enter a number: "))
print("Negative number entered. stop the program.")

Enter a number: 10
you entered: 10
Enter a number: -5
Negative number entered. stop the program.


In [ ]:
# find even number
numbers = [7,9,13,2,4,8,11,15]
for num in numbers:
    if num % 2 == 0:
        print(f"First even number is: {num}")
        break

First even number is: 2


In [ ]:
# add numbers until exceeds
numbers = [2,5,7,4,6,3,8,10]
limit = 20
total = 0
for num in numbers:
    if total + num > limit:
        break
    total += num
    last_number = num
print(f"last valid sum before exceeding: {total}")
print(f"last number added: {last_number}")


last valid sum before exceeding: 18
last number added: 4


In [ ]:
# guess the password
correct_password = "admin"
while True:
    guess = input("Enter the password: ")
    if guess == correct_password:
        print("Access granted!")
        break
    else:
        print("Wrong password .Try again.")


Enter the password: hello
Wrong password .Try again.
Enter the password: admin
Access granted!


In [ ]:
# multiplies of 7
i = 1
while True:
    result = 7*i
    if result > 100:
        break
    print(f"7 * {i} = {result}")
    i += 1

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
7 * 11 = 77
7 * 12 = 84
7 * 13 = 91
7 * 14 = 98


In [ ]:
# print num_digit until zero not found
number = input(" Enter a number: ")
for digit in number:
    if digit == '0':
        break
    print(digit)


 Enter a number: 45089
4
5


#### Assignment 3

In [ ]:
# Reverse the sentence
sentence = "I love python"
print(sentence.split())
reverse = ' '.join(sentence.split()[::-1])
print(sentence)
print(reverse)

['I', 'love', 'python']
I love python
python love I


In [ ]:
# Count consonants (ignoring case)
string = "Hello World"
vowels = "aeiou"
consonants = ""
count = 0
for char in string.lower():
    if char.isalpha() and char not in vowels:
        consonants += char
print ("Consonants string: ", consonants)
print ("Number of consonants: ", len(consonants))

Consonants string:  hllwrld
Number of consonants:  7


In [ ]:
# check string are anagrams or not
s1 = "Listen"
s2 = "Silent"
s1_sorted = sorted(s1.lower())
s2_sorted = sorted(s2.lower())
if s1_sorted == s2_sorted:
 print("Anagram")
else:
 print("Not Anagram")


Anagram


In [ ]:
# compressed string
s = "aaabbc"
compressed = ""
i = 0
while i < len(s):
    count = 1
    while i + 1 < len(s) and s[i] == s[i + 1]:
        count += 1
        i += 1
    compressed += s[i] + str(count)
    i += 1
print("Compressed string:", compressed)

Compressed string: a3b2c1


In [ ]:
# find char that appears only once
str = "programming"
count = [0] * 256   #ASCII value beacuse of case sensitive
for ch in str:
    count[ord(ch)] += 1
for ch in str:
    if count[ord(ch)] == 1:
        print("First non-repeating letter is:", ch)
        break
else:
    print("No non-repeating letter found")

First non-repeating letter is: p


In [ ]:
# longest substring
s = "babad"
longest = ""
for i in range(len(s)):
    for j in range(i, len(s)):
        sub = s[i:j+1]
        if sub == sub[::-1]:
            if len(sub) > len(longest):
                longest = sub
print("Longest palindrome:", longest)

Longest palindrome: bab


In [ ]:
# check sequence is valid or not
x = input("Enter a string: ")
s = []
dict = {')':'(', ']':'[', '}':'{'}
valid = True
for i in x:
    if i in '([{':
        s.append(i)
    elif i in ')]}':
        if not s and s[-1] != dict[i]:
            valid = False
            break
        s.pop()
if s:
    valid = False
print("valid" if valid else "Invalid")


Enter a string: ({[]})
valid


In [ ]:
#  Word ladder transformation
from collections import deque
start = "hit"
end = "cog"
wordList = ["hot", "dot", "dog", "lot", "log", "cog"]
wordSet = set(wordList)
queue = deque([(start, 1)])
while queue:
    word, steps = queue.popleft()
    if word == end:
        print(steps)
        break
for i in range(len(word)):
    for c in 'abcdefghijklmnopqrstuvwxyz':
        next_word = word[:i] + c + word[i+1:]
        if next_word in wordSet:
            wordSet.remove(next_word)
            queue.append((next_word, steps + 1))
else:
    print(0)

0


#### Assignment 4

In [ ]:
# print the dictionary items
dict = {'Ram': 80, 'Raman': 40, 'Ali': 78, 'Disha': 90, 'Sham': 55}
print(dict)
print(dict.keys())
print(dict.values())

{'Ram': 80, 'Raman': 40, 'Ali': 78, 'Disha': 90, 'Sham': 55}
dict_keys(['Ram', 'Raman', 'Ali', 'Disha', 'Sham'])
dict_values([80, 40, 78, 90, 55])


In [ ]:
# count frequency of character using dictionary
string = "Hello world!"
char_freq = {}                      # using dictionary
for char in string:
    if char in char_freq:
        char_freq[char] += 1
    else:
        char_freq[char] = 1
print(char_freq)

{'H': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1, '!': 1}


In [ ]:
# print name of oldest persons
person_age = {'Alice': 45, 'Sumit': 67, 'David': 34, 'Rani': 50, 'Sham': 35}
max_age = max(person_age.values())
print("oldest_person_age: ")
for name in person_age:
    if person_age[name] == max_age:
        print(name, "-",max_age)

oldest_person_age: 
Sumit - 67


In [ ]:
# merge the dictionary
dict1= {1:'a',2:'b',3:'c',4:'d'}
dict2= {5:'e',6:'f',7:'g',8:'h'}
# merge dict1 and dict2
dict3= dict1 |dict2
print(dict3)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h'}


In [ ]:
# or
dict1.update(dict2)
print(dict1)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h'}


In [ ]:
# dict. in which values are square of keys
squares = {}
for i in range(1,11):
    squares[i] = i * i
print("Number : Square")
for number, square in squares.items():
    print(number, ":", square)

Number : Square
1 : 1
2 : 4
3 : 9
4 : 16
5 : 25
6 : 36
7 : 49
8 : 64
9 : 81
10 : 100


In [ ]:
# swap the dictionary
dict = {1:'Ram', 2:'Sham', 3:'Rani', 4:'Taran', 5:'Manu'}
swap = {}
for key, value in dict.items():
    swap[value] = key
print("Swapped dict: ")
print(swap)

Swapped dict: 
{'Ram': 1, 'Sham': 2, 'Rani': 3, 'Taran': 4, 'Manu': 5}


In [ ]:
# nested dictionary
students = {
    "Alice": {"Math": 85, "English": 90, "Science": 78},
    "Bob": {"Math": 60, "English": 65, "Science": 70},
    "David": {"Math": 80, "English": 78, "Science": 50},
    "Charli": {"Math": 70, "English": 60, "Science": 80},
}
for name, subjects in students.items():
    total = sum(subjects.values())
    count = len(subjects)
    average = total/count
    print(f"{name} - Average Marks: {average:}")

Alice - Average Marks: 84.33333333333333
Bob - Average Marks: 65.0
David - Average Marks: 69.33333333333333
Charli - Average Marks: 70.0


In [ ]:
#  group words by their length from a list using a dictionary
words = ["apple", "car", "banana", "dog", "book", "eat"]
grouped = {}
for word in words:
    length = len(word)
    if length in grouped:
        grouped[length].append(word)
    else:
        grouped[length] = [word]
print("Words grouped by length:")
for length in sorted(grouped):
    print(f"Length {length}: {grouped[length]}")

Words grouped by length:
Length 3: ['car', 'dog', 'eat']
Length 4: ['book']
Length 5: ['apple']
Length 6: ['banana']


In [ ]:
# build dictionary from tupels
tuple = [("Alice", 85),("Bob", 90),("Alice", 95),("Bob", 80),("Charlei",70),("Charlei", 75),("Alice", 100)]
scores_dict = {}
for name, score in tuple:
    if name not in scores_dict:
        scores_dict[name] = []
    scores_dict[name].append(score)
for name, scores in scores_dict.items():
    average = sum(scores)/ len(scores)
    print(f"{name}'s average score: {average: }")

Alice's average score:  93.33333333333333
Bob's average score:  85.0
Charlei's average score:  72.5


#### Assignment 5

#### tuple() questions

In [ ]:
# create a tuple and find type
tuple = (1, "hello", 3.14, True, [1,2,3])
print(tuple)
print(type(tuple))

(1, 'hello', 3.14, True, [1, 2, 3])
<class 'tuple'>


In [ ]:
# to print second last element
t = (10,20, 30, 40, 50)
print(t[-2])

40


In [ ]:
# count the number of times  a given element appears in a tuple
tuple = (10, 20, 10, 30, 40, 10, 50)
element = int(input("Enter the element: "))
count = tuple.count(element)
print(f"The element {element} appears {count} times in tuple.")

Enter the element: 10
The element 10 appears 3 times in tuple.


In [ ]:
# convert a tuple of strings into a single string
tup_string = ('python', 'is', 'fun')
x = " ".join(tup_string)
print("The combined string is: ", x)

The combined string is:  python is fun


In [ ]:
#  find the index of an element in a tuple
tup = (10, 20, 30, 40, 50, 60)
element = int(input("Enter the element ti find its index: "))
if element in tup:
    index = tup.index(element)
    print(f"The index of {element} is: {index}")
else:
    print("The element not found in the tuple.")

Enter the element ti find its index: 40
The index of 40 is: 3


#### set() questions

In [ ]:
# perform union, intersection, and difference operations on set
set1 = {1,2,3,"hey",4.5,(5,6)}
set2 = {4,1,2,"good",9}
union = set1.union(set2)
intersection = set1.intersection(set2)
differnce = set1.difference(set2)
print("Set 1: ", set1)
print("Set 2: ", set2)
print("Union: ", union)
print("Intersection: ", intersection)
print("Differnce: ", differnce)

Set 1:  {1, 2, 3, 4.5, (5, 6), 'hey'}
Set 2:  {'good', 1, 2, 4, 9}
Union:  {1, 2, 3, 4.5, 4, 9, 'good', (5, 6), 'hey'}
Intersection:  {1, 2}
Differnce:  {3, 4.5, (5, 6), 'hey'}


In [ ]:
# or
union = set1 | set2
intersection = set1 & set2
differnce = set1 - set2
print("Set 1: ", set1)
print("Set 2: ", set2)
print("Union: ", union)
print("Intersection: ", intersection)
print("Differnce: ", differnce)

Set 1:  {1, 2, 3, 4.5, (5, 6), 'hey'}
Set 2:  {'good', 1, 2, 4, 9}
Union:  {1, 2, 3, 4.5, 4, 9, 'good', (5, 6), 'hey'}
Intersection:  {1, 2}
Differnce:  {3, 4.5, (5, 6), 'hey'}


In [ ]:
# check element is present or not
s = {10, 20, 40 ,50}
element = int(input("Enter element to check: "))
if element in s:
    print(f"{element} is present in the set.")
else:
    print(f"{element} is not present in the set.")

Enter element to check: 20
20 is present in the set.


In [ ]:
# symmetric difference between two sets
s1 = {1, 2, 3, 4, 5}
s2 = {4, 5, 6, 7, 8}
symm_diff = s1.symmetric_difference(s2)
print("Set 1: ", s1)
print("Set 2: ", s2)
print("Symmetric Difference: ", symm_diff )

Set 1:  {1, 2, 3, 4, 5}
Set 2:  {4, 5, 6, 7, 8}
Symmetric Difference:  {1, 2, 3, 6, 7, 8}


In [ ]:
# Remove duplicate elements from a list using a set
list_1 = [10, 20, 10, 30, 40, 20, 50]
unique_set = set(list_1)
unique_list = list(unique_set)
print("Original list: ", list_1)
print("List after remove duplicates: ", unique_list)

Original list:  [10, 20, 10, 30, 40, 20, 50]
List after remove duplicates:  [40, 10, 50, 20, 30]


In [ ]:
# or
symm_diff = s1 ^ s2
print("Set 1: ", s1)
print("Set 2: ", s2)
print("Symmetric Difference: ", symm_diff )

Set 1:  {1, 2, 3, 4, 5}
Set 2:  {4, 5, 6, 7, 8}
Symmetric Difference:  {1, 2, 3, 6, 7, 8}


In [ ]:
# find all unique elements using sets
numbers = [1, 2, 2, 3, 4, 4, 5, 5, 5, 5, 6]
unique = set(numbers)
print("Original list: ", numbers)
print("Unique elements: ", unique)

Original list:  [1, 2, 2, 3, 4, 4, 5, 5, 5, 5, 6]
Unique elements:  {1, 2, 3, 4, 5, 6}


#### Assignment 6

In [ ]:
# create a function() to find factorial
def fact(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result
n = 5
print("Factorial of", n, "is", fact(n))

Factorial of 5 is 120


In [ ]:
# check no. is prime or not
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
num = 7
if is_prime(num):
    print(num, "is a prime number.")
else:
    print(num, "is not a prime number.")

7 is a prime number.


In [ ]:
# takes a string as input and returns the number of vowels in it
def count_vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count
input_string = "Hello World"
print("Number of vowels:", count_vowels(input_string))

Number of vowels: 3


In [ ]:
# maximum and minimum values find
def find_max_min(numbers):
    return max(numbers), min(numbers)
num_list = [4, 9, 1, 7, 3]
maximum, minimum = find_max_min(num_list)
print("Maximum:", maximum)
print("Minimum:", minimum)

Maximum: 9
Minimum: 1


In [ ]:
# calculate the nth Fibonacci number
def fibonacci(n):
    if n <= 0:
        return "Invalid input"
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    a, b = 0, 1
    for _ in range(2, n):
        a, b = b, a + b
    return b
num = 7
print("Fibonacci number at position", num, "is", fibonacci(num))

Fibonacci number at position 7 is 8


In [ ]:
# accepts two numbers and returns their greatest common divisor (GCD)
def find_gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a
num1 = 36
num2 = 60
print("GCD of", num1, "and", num2, "is", find_gcd(num1, num2))

GCD of 36 and 60 is 12


In [ ]:
# takes a list and returns a new list with only unique elements
def unique_elements(lst):
    unique = []
    for item in lst:
        if item not in unique:
            unique.append(item)
    return unique
my_list = [1, 2, 2, 3, 4, 4, 5]
print("Unique elements:", unique_elements(my_list))

Unique elements: [1, 2, 3, 4, 5]


In [ ]:
# count the frequency of each word in a given string
def count_word_frequency(text):
    words = text.split()
    frequency = {}
    for word in words:
        if word in frequency:
            frequency[word] += 1
        else:
            frequency[word] = 1
    return frequency
input_text = "hello world hello world world"
result = count_word_frequency(input_text)
print("Word frequencies:", result)

Word frequencies: {'hello': 2, 'world': 3}


In [ ]:
# takes a number and returns True if it is a palindrome, otherwise False
def is_palindrome(num):
    num_str = str(num)
    return num_str == num_str[::-1]
number = 121
print("Is palindrome?", is_palindrome(number))

Is palindrome? True


In [ ]:
# Create a function that takes a temperature in Celsius and returns it in Fahrenheit
def celsius_to_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit
temp_c = 25
print("Temperature in Fahrenheit:", celsius_to_fahrenheit(temp_c))

Temperature in Fahrenheit: 77.0


#### Assignment 7

In [ ]:
# find largest element in list without  using max()
list1 = [34, 56, 70, 67, 50]
largest = list1[0]
for x in list1:
    if x > largest:
        largest = x
print("Largest element:", largest)

Largest element: 70


In [ ]:
# find smallest element in list without  using min()
list1 = [34, 56, 70, 67, 50]
smallest = list1[0]
for x in list1:
    if x < smallest:
        smallest = x
print("smallest element:",smallest)

smallest element: 34


In [ ]:
# find mean of elements in list
import statistics
data = [1,3,4,5,7,9]
x = statistics.mean(data)
print("Mean is: ", x)

Mean is:  4.833333333333333


In [ ]:
# find mean of elements in list without using mean function
list1= [10, 22, 3, 46, 5]
sum_num = 0
for t in list1:
    sum_num = sum_num + t
    avg= sum_num/len(list1)
print("The average is = ", avg)

The average is =  17.2


In [ ]:
# Find element in a list through Iinear search
x = int(input ("Enter an element to search In List: "))
list1= [10, 22, 3, 46, 5]
for i in range( len(list1)):
   if list1[i] == x:
     print("element found at index " + str(i))
     break
else:
   print("Element not found in list")

Enter an element to search In List: 46
element found at index 3


In [ ]:
# Count the frequency of elements in a list using dictionary
list = [1,1,7,5,5,3,7,3,3,4,4,4,4,4,2,4,2]
d = {}
for item in list:
    if item in d:
        d[item] += 1
    else:
        d[item] = 1
for key, value in d.items():
    print("%d: %d" % (key, value))

1: 2
7: 2
5: 2
3: 3
4: 6
2: 2


#### Assignment 8

In [ ]:
# create a new text file and write the text 'Hello, File Handling!' to it
f = open('example.txt' , 'w')
print(f.name)
f.close()
f.mode
with open('example.txt', 'w')as f:
    f.write('Hello, File Handling!')

example.txt


In [ ]:
# read the contents of 'example.txt' and display them on the screen
with open('example.txt', 'r')as f:
    f_contents = f.read()
    print( f_contents)
    f = open('abc.txt' , 'w')
print(f.name)
f.close()
with open('abc.txt', 'w')as f:
    f.write('Apple is a fruit.Banana is yellow.Ants are tiny.Zebra is an animal.A cat is cute.')

Hello, File Handling!
abc.txt


In [ ]:
#  read a file and print only those lines which start with the letter 'A'
with open("abc.txt", "r") as file:
    for line in file:
        if line.startswith("A"):
            print(line.strip())

Apple is a fruit.Banana is yellow.Ants are tiny.Zebra is an animal.A cat is cute.


In [ ]:
#  count the number of words in a given text file
with open("example.txt", "r") as file:
    content = file.read()
    words = content.split()
    word_count = len(words)
print("Number of words in the file:", word_count)

Number of words in the file: 3


In [ ]:
# merge the contents of two files into a third file
with open("abc.txt", "r") as file1:
    content1 = file1.read()
with open("example.txt", "r") as file2:
    content2 = file2.read()
with open("merged_file.txt", "w") as merged_file:
    merged_file.write(content1 + "\n" + content2)
print("Files merged successfully into 'merged_file.txt'.")

Files merged successfully into 'merged_file.txt'.


In [ ]:
# reads a text file and prints its content in reverse order (last line first)
with open("abc.txt", "r") as file:
    lines = file.readlines()
reversed_lines = lines[::-1]
for line in reversed_lines:
    print(line.strip())

Apple is a fruit.Banana is yellow.Ants are tiny.Zebra is an animal.A cat is cute.


In [ ]:
# find and replace a word in a file (e.g., replace 'old' with 'new').
with open("example.txt", "r") as file:
    content = file.read()
updated_content = content.replace("old", "new")
with open("example.txt", "w") as file:
    file.write(updated_content)
print("Word replaced successfully.")

Word replaced successfully.


In [ ]:
#  create a log file and append timestamps whenever the program is run
from datetime import datetime
current_time = datetime.now()
timestamp = current_time.strftime("%Y-%m-%d %H:%M:%S")
with open("log.txt", "a") as log_file:
    log_file.write(f"Program run at: {timestamp}\n")
print("Timestamp added to log file.")

Timestamp added to log file.


In [ ]:
# store and read student records (name and marks) from a file
with open("students.txt", "w") as file:
    students = [
        ("Alice", 85),
        ("Bob", 90),
        ("Charlie", 78)
    ]
    for name, marks in students:
        file.write(f"{name},{marks}\n")
print("Student records saved to file.")
with open("students.txt", "r") as file:
    print("\nStored Student Records:")
    for line in file:
        name, marks = line.strip().split(",")
        print(f"Name: {name}, Marks: {marks}")

Student records saved to file.

Stored Student Records:
Name: Alice, Marks: 85
Name: Bob, Marks: 90
Name: Charlie, Marks: 78


In [ ]:
with open('P69HiN.webp' , 'rb') as f:
    pass

In [ ]:
# copy an image file (binary mode) from one location to another
with open('P69HiN.webp', 'rb')as rf:
    with open('image_copy.jpg' , 'wb')as wf:
        for line in rf:
            wf.write(line)
print("Image copied successfully.")

Image copied successfully.


Assignment 9

In [ ]:
!pip install numpy
import numpy
print(numpy.__version__)

2.0.2


In [ ]:
# Create a NumPy array with values from 1 to 10. Print the shape, dimension, and data type of the array
import numpy as np
arr = np.arange(1,11)
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimension: 1
Data Type: int64


In [ ]:
#  3x3 NumPy array of all zeros and another of all ones. Then create a 3x3 identity matrix
zeros_arr = np.zeros((3,3))
print("Zeroes Array: \n", zeros_arr)
ones_arr = np.ones((3,3))
print("\nOnes Array: \n", ones_arr)
identity_matrix = np.eye(3)
print("\nIdentity matrix: \n", identity_matrix)

Zeroes Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#  15 random integers between 10 and 100 using np.random.randint. Reshape it into a 3x5 matrix and print it.
random_arr = np.random.randint(10, 101, size=15)
print("Random Array: \n", random_arr)
matrix_3x5 = random_arr.reshape(3, 5)
print("3x5 Random Integer Matrix:\n", matrix_3x5)

Random Array: 
 [47 61 67 96 94 30 38 64 73 13 16 17 16 67 87]
3x5 Random Integer Matrix:
 [[47 61 67 96 94]
 [30 38 64 73 13]
 [16 17 16 67 87]]


In [ ]:
# array from 1 to 20. Extract every 3rd element starting from index 1 using slicing
arr = np.arange(1,21)
print("Array:", arr)
sliced_arr = arr[1::3]
print("Sliced Array:", sliced_arr)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sliced Array: [ 2  5  8 11 14 17 20]


In [ ]:
# two arrays. Perform element-wise addition, multiplication, and compare which elements in a are greater than in b.
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
addition = a + b
multiplication = a * b
comparison = a > b
print("Array a:", a)
print("Array b:", b)
print("Addition:", addition)
print("Multiplication:", multiplication)
print("Comparison (a > b):", comparison)

Array a: [2 4 6 8]
Array b: [1 3 5 7]
Addition: [ 3  7 11 15]
Multiplication: [ 2 12 30 56]
Comparison (a > b): [ True  True  True  True]


In [ ]:
# Find the mean, median, standard deviation, min, and max
arr = np.random.rand(20)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Array: [0.38535776 0.18327999 0.15165965 0.39512604 0.4349299  0.67772613
 0.00576205 0.99771395 0.02997491 0.53226012 0.60105342 0.52550608
 0.96935183 0.67890785 0.64589274 0.13414495 0.63201217 0.09912209
 0.82978035 0.4496469 ]
Mean: 0.46796044467604736
Median: 0.4875764898811846
Standard Deviation: 0.2900651270309701
Minimum: 0.005762054554317997
Maximum: 0.9977139476504292


In [ ]:
# Find the sum across rows and columns using axis
arr = np.array([[3, 5], [7, 9]])
sum_rows = np.sum(arr, axis=1)
sum_columns = np.sum(arr, axis=0)
print("Array:\n", arr)
print("Sum Across Rows:", sum_rows)
print("Sum Across Columns:", sum_columns)

Array:
 [[3 5]
 [7 9]]
Sum Across Rows: [ 8 16]
Sum Across Columns: [10 14]


In [ ]:
# Filter and print only the even numbers using boolean indexing
arr = np.arange(10, 31)
even_numbers = arr[arr % 2 == 0]
print("Even numbers from 10 to 30:", even_numbers)

Even numbers from 10 to 30: [10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
# an array of 10 random integers from 1 to 100. Replace all elements greater than 50 with -1
arr = np.random.randint(1, 101, size=10)
print("Original array:", arr)
arr[arr > 50] = -1
print("Modified array:", arr)

Original array: [25 27  2 74 24 15 94 83 99 42]
Modified array: [25 27  2 -1 24 15 -1 -1 -1 42]


In [ ]:
# Stack them vertically and horizontally, then flatten the result into a 1D array
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((x, y))
horizontal_stack = np.hstack((x, y))
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)
flattened = horizontal_stack.flatten()
print("\nFlattened 1D Array:\n", flattened)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Flattened 1D Array:
 [1 2 5 6 3 4 7 8]


Assignment 10   (pandas)

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving diamonds.csv to diamonds (1).csv


In [ ]:
# Load the dataset and display the first 10 rows.
import pandas as pd
df = pd.read_csv('diamonds.csv')
print(df.head(10))

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39


In [ ]:
# Check the shape and column names of the dataset.
import pandas as pd
df = pd.read_csv('diamonds.csv')
print("Shape of the dataset:", df.shape)
print("Column names:", df.columns.tolist())

Shape of the dataset: (50000, 10)
Column names: ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']


In [ ]:
# Find and fill missing numeric values with their respective column means
df.fillna(df.mean(numeric_only=True), inplace=True)
print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64


In [ ]:
# Filter rows where `cut` is "Ideal" and `color` is "E"
filtered_df = df[(df['cut'] == 'Ideal') & (df['color'] == 'E')]
print("Filtered DataFrame:")
print(filtered_df)

Filtered DataFrame:
       carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
76      0.26  Ideal     E    VVS2   62.9   58.0    554  4.02  4.06  2.54
82      0.70  Ideal     E     SI1   62.5   57.0   2757  5.70  5.72  3.57
100     0.59  Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35
102     0.74  Ideal     E     SI2   62.2   56.0   2761  5.80  5.84  3.62
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
49940   0.70  Ideal     E     SI1   61.7   55.0   2745  5.71  5.74  3.53
49942   0.51  Ideal     E    VVS1   61.9   54.0   2745  5.17  5.11  3.18
49954   0.56  Ideal     E    VVS1   62.1   56.0   2750  5.28  5.29  3.28
49978   0.77  Ideal     E     SI2   62.1   56.0   2753  5.84  5.86  3.63
49987   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54

[3628 rows x 10 columns]


In [ ]:
# Group by `cut` and compute the average `price` for each group
grouped_df = df.groupby('cut')['price'].mean()
print("Average price for each cut:")
print(grouped_df)

Average price for each cut:
cut
Fair         4329.705017
Good         3961.470266
Ideal        3463.090230
Premium      4607.382867
Very Good    3986.585594
Name: price, dtype: float64


In [ ]:
# Sort the data by `carat` in descending order and show the top 5 rows
sorted_df = df.sort_values(by='carat', ascending=False)
print(sorted_df.head(5))

       carat      cut color clarity  depth  table  price      x      y     z
25426   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
25624   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
25163   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
24102   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
24103   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24


In [ ]:
# Convert the `price` column to a NumPy array and find its mean, median, and standard deviation
import numpy as np
price_array = df['price'].to_numpy()
mean_price = np.mean(price_array)
median_price = np.median(price_array)
std_dev_price = np.std(price_array)
print("Mean price:", mean_price)
print("Median price:", median_price)
print("Standard Deviation of price:", std_dev_price)

Mean price: 3944.80544
Median price: 2410.0
Standard Deviation of price: 3997.8981250585175


In [ ]:
# Count diamonds with `price > 5000` and `carat > 1` using NumPy conditions
price_array = df['price'].to_numpy()
carat_array = df['carat'].to_numpy()
condition = (price_array > 5000) & (carat_array > 1)
count = np.sum(condition)
print("Number of diamonds with price > 5000 and carat > 1:", count)

Number of diamonds with price > 5000 and carat > 1: 12798


In [ ]:
# Create a new column `price_updated` by increasing `price` by 10% using NumPy
price_updated_array = price_array * 1.10
df['price_updated'] = price_updated_array
print(df[['price', 'price_updated']])

       price  price_updated
0        326          358.6
1        326          358.6
2        327          359.7
3        334          367.4
4        335          368.5
...      ...            ...
49995   2757         3032.7
49996   2757         3032.7
49997   2757         3032.7
49998   2757         3032.7
49999   2757         3032.7

[50000 rows x 2 columns]


In [ ]:
# Create a `volume` column as `x*y*z` and find the average `price` where `volume > 50`
df['volume'] = df['x'] * df['y'] * df['z']
filtered_df = df[df['volume'] > 50]
average_price = filtered_df['price'].mean()
print("Average price where volume > 50:", average_price)

Average price where volume > 50: 4195.133420860057
